
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Sep 24 2024 21:40:14 -03 (Sep 25 2024 00:40:14 UTC)

// Verification Directory fv/top 

module top(q_serialized, start, clk, rst, enable, q_desired, i_ref_out);
  input q_serialized, start, clk, rst, enable;
  input [9:0] q_desired;
  output [9:0] i_ref_out;
  wire q_serialized, start, clk, rst, enable;
  wire [9:0] q_desired;
  wire [9:0] i_ref_out;
  wire [9:0] i_ref_w;
  wire [9:0] i_ref_max_w;
  wire [9:0] q_measured_w;
  wire i_ref_mux_w, ready_w, went_unstable_w;
  assign i_ref_mux_w = 1'b1;
  i_ref_mux_BUS_WIDTH10 i_ref_mux_inst(.i_ref (i_ref_w), .i_ref_max
       (i_ref_max_w), .went_unstable (went_unstable_w), .i_ref_out
       (i_ref_out));
  i_ref_sampling_BUS_WIDTH10 i_ref_sampling_inst(.i_ref (i_ref_w), .clk
       (clk), .rst (rst), .enable (enable), .ready (ready_w),
       .went_unstable (went_unstable_w), .i_ref_max (i_ref_max_w));
  bisection_BUS_WIDTH10_TOL1 q_control_inst(.clk (clk), .rst (rst),
       .enable (enable), .ready (ready_w), .i_ref_mux (i_ref_mux_w),
       .q_desired (q_desired), .q_measured (q_measured_w), .i_ref
       (i_ref_w), .went_unstable (went_unstable_w));
  q_measurement_BUS_WIDTH10_WTD_BUS_WIDTH2_Q_PER_PULSE30
       q_measurement_inst(.q_serialized (q_serialized), .clk (clk),
       .rst (rst), .start (start), .ready (ready_w), .q_measured
       (q_measured_w));
endmodule

