
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Sep 29 2024 14:31:48 -03 (Sep 29 2024 17:31:48 UTC)

// Verification Directory fv/top 

module top(q_serialized, start, clk, rst, enable, q_desired, i_ref_out);
  input q_serialized, start, clk, rst, enable;
  input [9:0] q_desired;
  output [9:0] i_ref_out;
  wire q_serialized, start, clk, rst, enable;
  wire [9:0] q_desired;
  wire [9:0] i_ref_out;
  wire [10:0] q_control_inst_error;
  wire [9:0] i_ref_w;
  wire [9:0] i_ref_max_w;
  wire [9:0] i_ref_sampling_inst_i_ref_smp_1;
  wire [9:0] i_ref_sampling_inst_i_ref_smp_2;
  wire [9:0] i_ref_sampling_inst_i_ref_smp_3;
  wire [9:0] i_ref_sampling_inst_i_ref_smp_4;
  wire [9:0] q_control_inst_a;
  wire [9:0] q_control_inst_b;
  wire [10:0] q_measurement_inst_q_pulses_count;
  wire [1:0] q_measurement_inst_wtd;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, n_2;
  wire n_3, n_4, n_6, n_7, n_8, n_9, n_10, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253,
       q_control_inst_converged;
  wire q_control_inst_n_902, q_control_inst_n_919,
       \q_measurement_inst_q_measured[0]_302 ,
       \q_measurement_inst_q_measured[0]_312 ,
       \q_measurement_inst_q_measured[1]_303 ,
       \q_measurement_inst_q_measured[1]_313 ,
       \q_measurement_inst_q_measured[2]_304 ,
       \q_measurement_inst_q_measured[2]_314 ;
  wire \q_measurement_inst_q_measured[3]_305 ,
       \q_measurement_inst_q_measured[3]_315 ,
       \q_measurement_inst_q_measured[4]_306 ,
       \q_measurement_inst_q_measured[4]_316 ,
       \q_measurement_inst_q_measured[5]_307 ,
       \q_measurement_inst_q_measured[5]_317 ,
       \q_measurement_inst_q_measured[6]_308 ,
       \q_measurement_inst_q_measured[6]_318 ;
  wire \q_measurement_inst_q_measured[7]_309 ,
       \q_measurement_inst_q_measured[7]_319 ,
       \q_measurement_inst_q_measured[8]_310 ,
       \q_measurement_inst_q_measured[8]_320 ,
       \q_measurement_inst_q_measured[9]_311 ,
       \q_measurement_inst_q_measured[9]_321 ,
       q_measurement_inst_wtd_lock, ready_w;
  wire went_unstable_w;
  assign went_unstable_w = 1'b0;
  TLATX1 \q_control_inst_error_reg[0] (.G (enable), .D (n_205), .Q
       (q_control_inst_error[0]), .QN (UNCONNECTED));
  TLATX1 \q_control_inst_error_reg[1] (.G (enable), .D (n_251), .Q
       (q_control_inst_error[1]), .QN (UNCONNECTED0));
  TLATX1 \q_control_inst_error_reg[2] (.G (enable), .D (n_252), .Q
       (q_control_inst_error[2]), .QN (UNCONNECTED1));
  TLATX1 \q_control_inst_error_reg[3] (.G (enable), .D (n_253), .Q
       (q_control_inst_error[3]), .QN (UNCONNECTED2));
  TLATX1 \q_control_inst_error_reg[4] (.G (enable), .D (n_250), .Q
       (q_control_inst_error[4]), .QN (UNCONNECTED3));
  TLATX1 \q_control_inst_error_reg[5] (.G (enable), .D (n_247), .Q
       (q_control_inst_error[5]), .QN (UNCONNECTED4));
  TLATX1 \q_control_inst_error_reg[6] (.G (enable), .D (n_248), .Q
       (q_control_inst_error[6]), .QN (UNCONNECTED5));
  TLATX1 \q_control_inst_error_reg[7] (.G (enable), .D (n_249), .Q
       (q_control_inst_error[7]), .QN (UNCONNECTED6));
  TLATX1 \q_control_inst_error_reg[8] (.G (enable), .D (n_246), .Q
       (q_control_inst_error[8]), .QN (UNCONNECTED7));
  TLATX1 \q_control_inst_error_reg[9] (.G (enable), .D (n_245), .Q
       (q_control_inst_error[9]), .QN (UNCONNECTED8));
  DFFQXL \q_measurement_inst_q_measured_reg[0] (.CK (clk), .D (1'b0),
       .Q (\q_measurement_inst_q_measured[0]_302 ));
  DFFSX1 \q_measurement_inst_q_measured_reg[0]109 (.SN (n_2), .CK
       (clk), .D (1'b0), .Q (UNCONNECTED9), .QN
       (\q_measurement_inst_q_measured[0]_312 ));
  DFFRX1 \q_measurement_inst_q_measured_reg[1]110 (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (UNCONNECTED10), .QN
       (\q_measurement_inst_q_measured[1]_313 ));
  DFFRX1 \q_measurement_inst_q_measured_reg[2]111 (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (UNCONNECTED11), .QN
       (\q_measurement_inst_q_measured[2]_314 ));
  DFFRX1 \q_measurement_inst_q_measured_reg[3]112 (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (UNCONNECTED12), .QN
       (\q_measurement_inst_q_measured[3]_315 ));
  DFFRX1 \q_measurement_inst_q_measured_reg[4]113 (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (UNCONNECTED13), .QN
       (\q_measurement_inst_q_measured[4]_316 ));
  DFFRX1 \q_measurement_inst_q_measured_reg[5]114 (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (UNCONNECTED14), .QN
       (\q_measurement_inst_q_measured[5]_317 ));
  DFFRX1 \q_measurement_inst_q_measured_reg[6]115 (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (UNCONNECTED15), .QN
       (\q_measurement_inst_q_measured[6]_318 ));
  DFFRX1 \q_measurement_inst_q_measured_reg[7]116 (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (UNCONNECTED16), .QN
       (\q_measurement_inst_q_measured[7]_319 ));
  DFFRX1 \q_measurement_inst_q_measured_reg[8]117 (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (UNCONNECTED17), .QN
       (\q_measurement_inst_q_measured[8]_320 ));
  DFFRX1 \q_measurement_inst_q_measured_reg[9]118 (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (UNCONNECTED18), .QN
       (\q_measurement_inst_q_measured[9]_321 ));
  XNOR2X1 g3051__2398(.A (n_217), .B (n_236), .Y (n_253));
  XNOR2X1 g3052__5107(.A (n_215), .B (n_240), .Y (n_252));
  XNOR2X1 g3053__6260(.A (n_210), .B (n_239), .Y (n_251));
  XNOR2X1 g3054__4319(.A (n_220), .B (n_242), .Y (n_250));
  XNOR2X1 g3055__8428(.A (n_229), .B (n_241), .Y (n_249));
  XNOR2X1 g3056__5526(.A (n_226), .B (n_244), .Y (n_248));
  XNOR2X1 g3057__6783(.A (n_223), .B (n_243), .Y (n_247));
  XNOR2X1 g3058__3680(.A (n_232), .B (n_238), .Y (n_246));
  XNOR2X1 g3059__1617(.A (n_234), .B (n_237), .Y (n_245));
  NAND2XL g3060__2802(.A (n_225), .B (q_control_inst_n_919), .Y
       (n_244));
  NOR2XL g3061__1705(.A (n_222), .B (n_235), .Y (n_243));
  NAND2XL g3062__5122(.A (n_213), .B (q_control_inst_n_919), .Y
       (n_242));
  NOR2XL g3063__8246(.A (n_228), .B (n_235), .Y (n_241));
  NAND2XL g3064__7098(.A (n_214), .B (q_control_inst_n_919), .Y
       (n_240));
  NAND2XL g3065__6131(.A (n_205), .B (q_control_inst_n_919), .Y
       (n_239));
  NAND2XL g3066__1881(.A (n_231), .B (q_control_inst_n_919), .Y
       (n_238));
  OAI21XL g3067__5115(.A0 (n_231), .A1 (n_232), .B0
       (q_control_inst_n_919), .Y (n_237));
  OAI21XL g3068__7482(.A0 (n_215), .A1 (n_214), .B0
       (q_control_inst_n_919), .Y (n_236));
  INVX1 g3069(.A (q_control_inst_n_919), .Y (n_235));
  NAND2BX1 g3070__4733(.AN (n_219), .B (q_control_inst_n_902), .Y
       (q_control_inst_n_919));
  OAI22X1 g3071__6161(.A0 (n_194), .A1 (n_233), .B0 (q_desired[9]), .B1
       (n_180), .Y (q_control_inst_n_902));
  XNOR2X1 g3072__9315(.A (n_207), .B (n_233), .Y (n_234));
  AOI22X1 g3073__9945(.A0 (n_186), .A1 (n_230), .B0 (n_171), .B1
       (n_197), .Y (n_233));
  CLKXOR2X1 g3074__2883(.A (n_202), .B (n_230), .Y (n_232));
  NAND2XL g3075__2346(.A (n_228), .B (n_229), .Y (n_231));
  OAI22X1 g3076__1666(.A0 (n_193), .A1 (n_227), .B0 (q_desired[7]), .B1
       (n_176), .Y (n_230));
  CLKXOR2X1 g3077__7410(.A (n_200), .B (n_227), .Y (n_229));
  NOR2XL g3078__6417(.A (n_225), .B (n_226), .Y (n_228));
  AOI22X1 g3079__5477(.A0 (n_188), .A1 (n_224), .B0 (n_170), .B1
       (n_198), .Y (n_227));
  CLKXOR2X1 g3080__2398(.A (n_203), .B (n_224), .Y (n_226));
  NAND2XL g3081__5107(.A (n_222), .B (n_223), .Y (n_225));
  OAI22X1 g3082__6260(.A0 (n_189), .A1 (n_221), .B0 (q_desired[5]), .B1
       (n_178), .Y (n_224));
  CLKXOR2X1 g3083__4319(.A (n_201), .B (n_221), .Y (n_223));
  NOR2XL g3084__8428(.A (n_213), .B (n_220), .Y (n_222));
  AOI22X1 g3085__5526(.A0 (n_187), .A1 (n_218), .B0 (n_173), .B1
       (n_196), .Y (n_221));
  CLKXOR2X1 g3086__6783(.A (n_199), .B (n_218), .Y (n_220));
  NOR4BBX1 g3087__3680(.AN (n_201), .BN (n_207), .C (n_212), .D
       (n_213), .Y (n_219));
  XNOR2X1 g3088__1617(.A (n_209), .B (n_216), .Y (n_217));
  OAI22X1 g3089__2802(.A0 (n_185), .A1 (n_216), .B0 (q_desired[3]), .B1
       (n_174), .Y (n_218));
  AOI22X1 g3090__1705(.A0 (n_184), .A1 (n_211), .B0 (n_172), .B1
       (n_204), .Y (n_216));
  CLKXOR2X1 g3091__5122(.A (n_206), .B (n_211), .Y (n_215));
  OR2X1 g3092__8246(.A (n_205), .B (n_210), .Y (n_214));
  NAND4XL g3093__7098(.A (n_199), .B (n_203), .C (n_200), .D (n_202),
       .Y (n_212));
  NAND4BX1 g3094__6131(.AN (n_205), .B (n_206), .C (n_208), .D (n_209),
       .Y (n_213));
  OAI22X1 g3095__1881(.A0 (n_192), .A1 (n_195), .B0 (q_desired[1]), .B1
       (n_182), .Y (n_211));
  XNOR2X1 g3096__5115(.A (n_195), .B (n_208), .Y (n_210));
  MXI2XL g3098__7482(.A (n_175), .B (n_174), .S0 (q_desired[3]), .Y
       (n_209));
  MXI2XL g3099__4733(.A (n_183), .B (n_182), .S0 (q_desired[1]), .Y
       (n_208));
  MXI2XL g3100__6161(.A (n_181), .B (n_180), .S0 (q_desired[9]), .Y
       (n_207));
  MXI2XL g3101__9315(.A (q_desired[2]), .B (n_172), .S0 (n_204), .Y
       (n_206));
  NAND2BX1 g3102__9945(.AN (n_195), .B (n_191), .Y (n_205));
  MXI2XL g3103__2883(.A (q_desired[6]), .B (n_170), .S0 (n_198), .Y
       (n_203));
  MXI2XL g3104__2346(.A (q_desired[8]), .B (n_171), .S0 (n_197), .Y
       (n_202));
  MXI2XL g3105__1666(.A (n_179), .B (n_178), .S0 (q_desired[5]), .Y
       (n_201));
  MXI2XL g3106__7410(.A (n_177), .B (n_176), .S0 (q_desired[7]), .Y
       (n_200));
  MXI2XL g3107__6417(.A (q_desired[4]), .B (n_173), .S0 (n_196), .Y
       (n_199));
  NOR2BX1 g3108__5477(.AN (q_desired[9]), .B (n_181), .Y (n_194));
  NOR2BX1 g3109__2398(.AN (q_desired[7]), .B (n_177), .Y (n_193));
  NOR2BX1 g3110__5107(.AN (q_desired[1]), .B (n_183), .Y (n_192));
  NAND2BX1 g3111__6260(.AN (q_desired[0]), .B (n_190), .Y (n_191));
  NOR2BX1 g3112__4319(.AN (q_desired[0]), .B (n_190), .Y (n_195));
  NOR2BX1 g3113__8428(.AN (q_desired[5]), .B (n_179), .Y (n_189));
  OR2XL g3114__5526(.A (n_170), .B (n_198), .Y (n_188));
  OR2XL g3115__6783(.A (n_173), .B (n_196), .Y (n_187));
  OR2XL g3116__3680(.A (n_171), .B (n_197), .Y (n_186));
  NOR2BX1 g3117__1617(.AN (q_desired[3]), .B (n_175), .Y (n_185));
  OR2XL g3118__2802(.A (n_172), .B (n_204), .Y (n_184));
  INVX1 g3119(.A (n_183), .Y (n_182));
  INVX1 g3120(.A (n_181), .Y (n_180));
  INVX1 g3121(.A (n_179), .Y (n_178));
  INVX1 g3122(.A (n_177), .Y (n_176));
  INVX1 g3123(.A (n_175), .Y (n_174));
  TBUFXL q_measurement_inst_g47__1705(.A
       (\q_measurement_inst_q_measured[0]_302 ), .OE
       (\q_measurement_inst_q_measured[0]_312 ), .Y (n_190));
  TBUFX1 q_measurement_inst_g46__5122(.A
       (\q_measurement_inst_q_measured[1]_303 ), .OE
       (\q_measurement_inst_q_measured[1]_313 ), .Y (n_183));
  TBUFX1 q_measurement_inst_g38__8246(.A
       (\q_measurement_inst_q_measured[9]_311 ), .OE
       (\q_measurement_inst_q_measured[9]_321 ), .Y (n_181));
  TBUFX1 q_measurement_inst_g39__7098(.A
       (\q_measurement_inst_q_measured[8]_310 ), .OE
       (\q_measurement_inst_q_measured[8]_320 ), .Y (n_197));
  TBUFX1 q_measurement_inst_g41__6131(.A
       (\q_measurement_inst_q_measured[6]_308 ), .OE
       (\q_measurement_inst_q_measured[6]_318 ), .Y (n_198));
  TBUFX1 q_measurement_inst_g42__1881(.A
       (\q_measurement_inst_q_measured[5]_307 ), .OE
       (\q_measurement_inst_q_measured[5]_317 ), .Y (n_179));
  TBUFX1 q_measurement_inst_g43__5115(.A
       (\q_measurement_inst_q_measured[4]_306 ), .OE
       (\q_measurement_inst_q_measured[4]_316 ), .Y (n_196));
  TBUFX1 q_measurement_inst_g40__7482(.A
       (\q_measurement_inst_q_measured[7]_309 ), .OE
       (\q_measurement_inst_q_measured[7]_319 ), .Y (n_177));
  TBUFX1 q_measurement_inst_g44__4733(.A
       (\q_measurement_inst_q_measured[3]_305 ), .OE
       (\q_measurement_inst_q_measured[3]_315 ), .Y (n_175));
  TBUFX1 q_measurement_inst_g45__6161(.A
       (\q_measurement_inst_q_measured[2]_304 ), .OE
       (\q_measurement_inst_q_measured[2]_314 ), .Y (n_204));
  MX2XL g3124__9315(.A (i_ref_w[3]), .B (i_ref_max_w[3]), .S0
       (went_unstable_w), .Y (i_ref_out[3]));
  MX2XL g3125__9945(.A (i_ref_w[6]), .B (i_ref_max_w[6]), .S0
       (went_unstable_w), .Y (i_ref_out[6]));
  MX2XL g3126__2883(.A (i_ref_w[2]), .B (i_ref_max_w[2]), .S0
       (went_unstable_w), .Y (i_ref_out[2]));
  MX2XL g3127__2346(.A (i_ref_w[1]), .B (i_ref_max_w[1]), .S0
       (went_unstable_w), .Y (i_ref_out[1]));
  MX2XL g3128__1666(.A (i_ref_w[5]), .B (i_ref_max_w[5]), .S0
       (went_unstable_w), .Y (i_ref_out[5]));
  MX2XL g3129__7410(.A (i_ref_w[7]), .B (i_ref_max_w[7]), .S0
       (went_unstable_w), .Y (i_ref_out[7]));
  MX2XL g3130__6417(.A (i_ref_w[0]), .B (i_ref_max_w[0]), .S0
       (went_unstable_w), .Y (i_ref_out[0]));
  MX2XL g3131__5477(.A (i_ref_w[4]), .B (i_ref_max_w[4]), .S0
       (went_unstable_w), .Y (i_ref_out[4]));
  MX2XL g3132__2398(.A (i_ref_w[8]), .B (i_ref_max_w[8]), .S0
       (went_unstable_w), .Y (i_ref_out[8]));
  MX2XL g3133__5107(.A (i_ref_w[9]), .B (i_ref_max_w[9]), .S0
       (went_unstable_w), .Y (i_ref_out[9]));
  INVX1 g3145(.A (q_desired[4]), .Y (n_173));
  INVX1 g3146(.A (q_desired[2]), .Y (n_172));
  INVX1 g3147(.A (q_desired[8]), .Y (n_171));
  INVX1 g3148(.A (q_desired[6]), .Y (n_170));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_max_reg[0] (.SN (n_2), .CK (clk),
       .D (n_30), .Q (i_ref_max_w[0]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_max_reg[1] (.SN (n_2), .CK (clk),
       .D (n_27), .Q (i_ref_max_w[1]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_max_reg[2] (.SN (n_2), .CK (clk),
       .D (n_32), .Q (i_ref_max_w[2]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_max_reg[3] (.SN (n_2), .CK (clk),
       .D (n_33), .Q (i_ref_max_w[3]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_max_reg[4] (.SN (n_2), .CK (clk),
       .D (n_29), .Q (i_ref_max_w[4]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_max_reg[5] (.SN (n_2), .CK (clk),
       .D (n_28), .Q (i_ref_max_w[5]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_max_reg[6] (.SN (n_2), .CK (clk),
       .D (n_26), .Q (i_ref_max_w[6]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_max_reg[7] (.SN (n_2), .CK (clk),
       .D (n_34), .Q (i_ref_max_w[7]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_max_reg[8] (.SN (n_2), .CK (clk),
       .D (n_31), .Q (i_ref_max_w[8]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_max_reg[9] (.SN (n_2), .CK (clk),
       .D (n_25), .Q (i_ref_max_w[9]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_1_reg[0] (.SN (n_2), .CK
       (clk), .D (n_44), .Q (i_ref_sampling_inst_i_ref_smp_1[0]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_1_reg[1] (.SN (n_2), .CK
       (clk), .D (n_81), .Q (i_ref_sampling_inst_i_ref_smp_1[1]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_1_reg[2] (.SN (n_2), .CK
       (clk), .D (n_78), .Q (i_ref_sampling_inst_i_ref_smp_1[2]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_1_reg[3] (.SN (n_2), .CK
       (clk), .D (n_73), .Q (i_ref_sampling_inst_i_ref_smp_1[3]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_1_reg[4] (.SN (n_2), .CK
       (clk), .D (n_70), .Q (i_ref_sampling_inst_i_ref_smp_1[4]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_1_reg[5] (.SN (n_2), .CK
       (clk), .D (n_66), .Q (i_ref_sampling_inst_i_ref_smp_1[5]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_1_reg[6] (.SN (n_2), .CK
       (clk), .D (n_69), .Q (i_ref_sampling_inst_i_ref_smp_1[6]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_1_reg[7] (.SN (n_2), .CK
       (clk), .D (n_65), .Q (i_ref_sampling_inst_i_ref_smp_1[7]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_1_reg[8] (.SN (n_2), .CK
       (clk), .D (n_79), .Q (i_ref_sampling_inst_i_ref_smp_1[8]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_1_reg[9] (.SN (n_2), .CK
       (clk), .D (n_77), .Q (i_ref_sampling_inst_i_ref_smp_1[9]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_2_reg[0] (.SN (n_2), .CK
       (clk), .D (n_63), .Q (i_ref_sampling_inst_i_ref_smp_2[0]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_2_reg[1] (.SN (n_2), .CK
       (clk), .D (n_61), .Q (i_ref_sampling_inst_i_ref_smp_2[1]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_2_reg[2] (.SN (n_2), .CK
       (clk), .D (n_59), .Q (i_ref_sampling_inst_i_ref_smp_2[2]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_2_reg[3] (.SN (n_2), .CK
       (clk), .D (n_58), .Q (i_ref_sampling_inst_i_ref_smp_2[3]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_2_reg[4] (.SN (n_2), .CK
       (clk), .D (n_57), .Q (i_ref_sampling_inst_i_ref_smp_2[4]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_2_reg[5] (.SN (n_2), .CK
       (clk), .D (n_54), .Q (i_ref_sampling_inst_i_ref_smp_2[5]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_2_reg[6] (.SN (n_2), .CK
       (clk), .D (n_56), .Q (i_ref_sampling_inst_i_ref_smp_2[6]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_2_reg[7] (.SN (n_2), .CK
       (clk), .D (n_53), .Q (i_ref_sampling_inst_i_ref_smp_2[7]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_2_reg[8] (.SN (n_2), .CK
       (clk), .D (n_52), .Q (i_ref_sampling_inst_i_ref_smp_2[8]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_2_reg[9] (.SN (n_2), .CK
       (clk), .D (n_51), .Q (i_ref_sampling_inst_i_ref_smp_2[9]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_3_reg[0] (.SN (n_2), .CK
       (clk), .D (n_50), .Q (i_ref_sampling_inst_i_ref_smp_3[0]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_3_reg[1] (.SN (n_2), .CK
       (clk), .D (n_49), .Q (i_ref_sampling_inst_i_ref_smp_3[1]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_3_reg[2] (.SN (n_2), .CK
       (clk), .D (n_48), .Q (i_ref_sampling_inst_i_ref_smp_3[2]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_3_reg[3] (.SN (n_2), .CK
       (clk), .D (n_46), .Q (i_ref_sampling_inst_i_ref_smp_3[3]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_3_reg[4] (.SN (n_2), .CK
       (clk), .D (n_45), .Q (i_ref_sampling_inst_i_ref_smp_3[4]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_3_reg[5] (.SN (n_2), .CK
       (clk), .D (n_60), .Q (i_ref_sampling_inst_i_ref_smp_3[5]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_3_reg[6] (.SN (n_2), .CK
       (clk), .D (n_43), .Q (i_ref_sampling_inst_i_ref_smp_3[6]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_3_reg[7] (.SN (n_2), .CK
       (clk), .D (n_80), .Q (i_ref_sampling_inst_i_ref_smp_3[7]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_3_reg[8] (.SN (n_2), .CK
       (clk), .D (n_62), .Q (i_ref_sampling_inst_i_ref_smp_3[8]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_3_reg[9] (.SN (n_2), .CK
       (clk), .D (n_76), .Q (i_ref_sampling_inst_i_ref_smp_3[9]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_4_reg[0] (.SN (n_2), .CK
       (clk), .D (n_75), .Q (i_ref_sampling_inst_i_ref_smp_4[0]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_4_reg[1] (.SN (n_2), .CK
       (clk), .D (n_74), .Q (i_ref_sampling_inst_i_ref_smp_4[1]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_4_reg[2] (.SN (n_2), .CK
       (clk), .D (n_72), .Q (i_ref_sampling_inst_i_ref_smp_4[2]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_4_reg[3] (.SN (n_2), .CK
       (clk), .D (n_55), .Q (i_ref_sampling_inst_i_ref_smp_4[3]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_4_reg[4] (.SN (n_2), .CK
       (clk), .D (n_71), .Q (i_ref_sampling_inst_i_ref_smp_4[4]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_4_reg[5] (.SN (n_2), .CK
       (clk), .D (n_64), .Q (i_ref_sampling_inst_i_ref_smp_4[5]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_4_reg[6] (.SN (n_2), .CK
       (clk), .D (n_47), .Q (i_ref_sampling_inst_i_ref_smp_4[6]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_4_reg[7] (.SN (n_2), .CK
       (clk), .D (n_84), .Q (i_ref_sampling_inst_i_ref_smp_4[7]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_4_reg[8] (.SN (n_2), .CK
       (clk), .D (n_68), .Q (i_ref_sampling_inst_i_ref_smp_4[8]));
  DFFSHQX1 \i_ref_sampling_inst_i_ref_smp_4_reg[9] (.SN (n_2), .CK
       (clk), .D (n_67), .Q (i_ref_sampling_inst_i_ref_smp_4[9]));
  SDFFRHQX1 \q_control_inst_a_reg[0] (.RN (n_2), .CK (clk), .D
       (q_control_inst_a[0]), .SI (i_ref_w[0]), .SE (n_103), .Q
       (q_control_inst_a[0]));
  SDFFRHQX1 \q_control_inst_a_reg[1] (.RN (n_2), .CK (clk), .D
       (q_control_inst_a[1]), .SI (i_ref_w[1]), .SE (n_103), .Q
       (q_control_inst_a[1]));
  SDFFRHQX1 \q_control_inst_a_reg[2] (.RN (n_2), .CK (clk), .D
       (q_control_inst_a[2]), .SI (i_ref_w[2]), .SE (n_103), .Q
       (q_control_inst_a[2]));
  SDFFRHQX1 \q_control_inst_a_reg[3] (.RN (n_2), .CK (clk), .D
       (q_control_inst_a[3]), .SI (i_ref_w[3]), .SE (n_103), .Q
       (q_control_inst_a[3]));
  SDFFRHQX1 \q_control_inst_a_reg[4] (.RN (n_2), .CK (clk), .D
       (q_control_inst_a[4]), .SI (i_ref_w[4]), .SE (n_103), .Q
       (q_control_inst_a[4]));
  SDFFRHQX1 \q_control_inst_a_reg[5] (.RN (n_2), .CK (clk), .D
       (q_control_inst_a[5]), .SI (i_ref_w[5]), .SE (n_103), .Q
       (q_control_inst_a[5]));
  SDFFRHQX1 \q_control_inst_a_reg[6] (.RN (n_2), .CK (clk), .D
       (q_control_inst_a[6]), .SI (i_ref_w[6]), .SE (n_103), .Q
       (q_control_inst_a[6]));
  SDFFRHQX1 \q_control_inst_a_reg[7] (.RN (n_2), .CK (clk), .D
       (q_control_inst_a[7]), .SI (i_ref_w[7]), .SE (n_103), .Q
       (q_control_inst_a[7]));
  SDFFRHQX1 \q_control_inst_a_reg[8] (.RN (n_2), .CK (clk), .D
       (q_control_inst_a[8]), .SI (i_ref_w[8]), .SE (n_103), .Q
       (q_control_inst_a[8]));
  SDFFRHQX1 \q_control_inst_a_reg[9] (.RN (n_2), .CK (clk), .D
       (q_control_inst_a[9]), .SI (i_ref_w[9]), .SE (n_103), .Q
       (q_control_inst_a[9]));
  DFFSHQX1 \q_control_inst_b_reg[0] (.SN (n_2), .CK (clk), .D (n_114),
       .Q (q_control_inst_b[0]));
  DFFSHQX1 \q_control_inst_b_reg[1] (.SN (n_2), .CK (clk), .D (n_115),
       .Q (q_control_inst_b[1]));
  DFFSHQX1 \q_control_inst_b_reg[2] (.SN (n_2), .CK (clk), .D (n_109),
       .Q (q_control_inst_b[2]));
  DFFSHQX1 \q_control_inst_b_reg[3] (.SN (n_2), .CK (clk), .D (n_112),
       .Q (q_control_inst_b[3]));
  DFFSHQX1 \q_control_inst_b_reg[4] (.SN (n_2), .CK (clk), .D (n_111),
       .Q (q_control_inst_b[4]));
  DFFSHQX1 \q_control_inst_b_reg[5] (.SN (n_2), .CK (clk), .D (n_110),
       .Q (q_control_inst_b[5]));
  DFFSHQX1 \q_control_inst_b_reg[6] (.SN (n_2), .CK (clk), .D (n_113),
       .Q (q_control_inst_b[6]));
  DFFSHQX1 \q_control_inst_b_reg[7] (.SN (n_2), .CK (clk), .D (n_106),
       .Q (q_control_inst_b[7]));
  DFFSHQX1 \q_control_inst_b_reg[8] (.SN (n_2), .CK (clk), .D (n_108),
       .Q (q_control_inst_b[8]));
  DFFSHQX1 \q_control_inst_b_reg[9] (.SN (n_2), .CK (clk), .D (n_107),
       .Q (q_control_inst_b[9]));
  SDFFSRX1 \q_control_inst_c_reg[0] (.RN (n_101), .SN (n_102), .CK
       (clk), .D (i_ref_w[0]), .SI (n_94), .SE (n_36), .Q (i_ref_w[0]),
       .QN (UNCONNECTED19));
  SDFFSRX1 \q_control_inst_c_reg[1] (.RN (n_122), .SN (n_123), .CK
       (clk), .D (i_ref_w[1]), .SI (n_118), .SE (n_36), .Q
       (i_ref_w[1]), .QN (UNCONNECTED20));
  SDFFSRX1 \q_control_inst_c_reg[2] (.RN (n_129), .SN (n_128), .CK
       (clk), .D (i_ref_w[2]), .SI (n_126), .SE (n_36), .Q
       (i_ref_w[2]), .QN (UNCONNECTED21));
  SDFFSRX1 \q_control_inst_c_reg[3] (.RN (n_136), .SN (n_137), .CK
       (clk), .D (i_ref_w[3]), .SI (n_134), .SE (n_36), .Q
       (i_ref_w[3]), .QN (UNCONNECTED22));
  SDFFSRX1 \q_control_inst_c_reg[4] (.RN (n_145), .SN (n_144), .CK
       (clk), .D (i_ref_w[4]), .SI (n_142), .SE (n_36), .Q
       (i_ref_w[4]), .QN (UNCONNECTED23));
  SDFFSRX1 \q_control_inst_c_reg[5] (.RN (n_152), .SN (n_153), .CK
       (clk), .D (i_ref_w[5]), .SI (n_150), .SE (n_36), .Q
       (i_ref_w[5]), .QN (UNCONNECTED24));
  SDFFSRX1 \q_control_inst_c_reg[6] (.RN (n_157), .SN (n_156), .CK
       (clk), .D (i_ref_w[6]), .SI (n_155), .SE (n_36), .Q
       (i_ref_w[6]), .QN (UNCONNECTED25));
  SDFFSRX1 \q_control_inst_c_reg[7] (.RN (n_161), .SN (n_160), .CK
       (clk), .D (i_ref_w[7]), .SI (n_159), .SE (n_36), .Q
       (i_ref_w[7]), .QN (UNCONNECTED26));
  SDFFSRX1 \q_control_inst_c_reg[8] (.RN (n_166), .SN (n_167), .CK
       (clk), .D (i_ref_w[8]), .SI (n_163), .SE (n_36), .Q
       (i_ref_w[8]), .QN (UNCONNECTED27));
  SDFFSRX1 \q_control_inst_c_reg[9] (.RN (n_165), .SN (n_164), .CK
       (clk), .D (i_ref_w[9]), .SI (n_162), .SE (n_36), .Q
       (i_ref_w[9]), .QN (UNCONNECTED28));
  DFFRHQX1 q_control_inst_converged_reg(.RN (n_2), .CK (clk), .D
       (n_104), .Q (q_control_inst_converged));
  SDFFRHQX1 \q_measurement_inst_q_measured_reg[1] (.RN (n_2), .CK
       (clk), .D (q_measurement_inst_q_pulses_count[0]), .SI
       (\q_measurement_inst_q_measured[1]_303 ), .SE (n_38), .Q
       (\q_measurement_inst_q_measured[1]_303 ));
  SDFFRHQX1 \q_measurement_inst_q_measured_reg[2] (.RN (n_2), .CK
       (clk), .D (n_41), .SI (\q_measurement_inst_q_measured[2]_304 ),
       .SE (n_38), .Q (\q_measurement_inst_q_measured[2]_304 ));
  DFFRHQX1 \q_measurement_inst_q_measured_reg[3] (.RN (n_2), .CK (clk),
       .D (n_98), .Q (\q_measurement_inst_q_measured[3]_305 ));
  SDFFRHQX1 \q_measurement_inst_q_measured_reg[4] (.RN (n_2), .CK
       (clk), .D (n_97), .SI (\q_measurement_inst_q_measured[4]_306 ),
       .SE (n_38), .Q (\q_measurement_inst_q_measured[4]_306 ));
  SDFFRHQX1 \q_measurement_inst_q_measured_reg[5] (.RN (n_2), .CK
       (clk), .D (n_121), .SI (\q_measurement_inst_q_measured[5]_307 ),
       .SE (n_38), .Q (\q_measurement_inst_q_measured[5]_307 ));
  SDFFRHQX1 \q_measurement_inst_q_measured_reg[6] (.RN (n_2), .CK
       (clk), .D (n_131), .SI (\q_measurement_inst_q_measured[6]_308 ),
       .SE (n_38), .Q (\q_measurement_inst_q_measured[6]_308 ));
  SDFFRHQX1 \q_measurement_inst_q_measured_reg[7] (.RN (n_2), .CK
       (clk), .D (n_139), .SI (\q_measurement_inst_q_measured[7]_309 ),
       .SE (n_38), .Q (\q_measurement_inst_q_measured[7]_309 ));
  SDFFRHQX1 \q_measurement_inst_q_measured_reg[8] (.RN (n_2), .CK
       (clk), .D (n_147), .SI (\q_measurement_inst_q_measured[8]_310 ),
       .SE (n_38), .Q (\q_measurement_inst_q_measured[8]_310 ));
  SDFFRHQX1 \q_measurement_inst_q_measured_reg[9] (.RN (n_2), .CK
       (clk), .D (n_148), .SI (\q_measurement_inst_q_measured[9]_311 ),
       .SE (n_38), .Q (\q_measurement_inst_q_measured[9]_311 ));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[0]90 (.RN (n_3), .CK
       (q_serialized), .D (n_6), .Q
       (q_measurement_inst_q_pulses_count[0]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[1]91 (.RN (n_3), .CK
       (q_serialized), .D (n_41), .Q
       (q_measurement_inst_q_pulses_count[1]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[2]92 (.RN (n_3), .CK
       (q_serialized), .D (n_82), .Q
       (q_measurement_inst_q_pulses_count[2]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[3]93 (.RN (n_3), .CK
       (q_serialized), .D (n_96), .Q
       (q_measurement_inst_q_pulses_count[3]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[4]94 (.RN (n_3), .CK
       (q_serialized), .D (n_120), .Q
       (q_measurement_inst_q_pulses_count[4]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[5]95 (.RN (n_3), .CK
       (q_serialized), .D (n_127), .Q
       (q_measurement_inst_q_pulses_count[5]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[6]96 (.RN (n_3), .CK
       (q_serialized), .D (n_135), .Q
       (q_measurement_inst_q_pulses_count[6]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[7]97 (.RN (n_3), .CK
       (q_serialized), .D (n_143), .Q
       (q_measurement_inst_q_pulses_count[7]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[8]98 (.RN (n_3), .CK
       (q_serialized), .D (n_151), .Q
       (q_measurement_inst_q_pulses_count[8]));
  DFFRHQX1 q_measurement_inst_ready_reg(.RN (n_2), .CK (clk), .D
       (n_83), .Q (ready_w));
  DFFSHQX1 \q_measurement_inst_wtd_reg[0] (.SN (n_2), .CK (clk), .D
       (n_4), .Q (q_measurement_inst_wtd[0]));
  DFFSHQX1 \q_measurement_inst_wtd_reg[1] (.SN (n_2), .CK (clk), .D
       (n_105), .Q (q_measurement_inst_wtd[1]));
  NAND2XL g3314__6260(.A (rst), .B (n_163), .Y (n_167));
  NAND2BXL g3315__4319(.AN (n_163), .B (rst), .Y (n_166));
  NAND2BXL g3316__8428(.AN (n_162), .B (rst), .Y (n_165));
  NAND2XL g3317__5526(.A (rst), .B (n_162), .Y (n_164));
  ADDFX1 g3318__6783(.A (q_control_inst_a[9]), .B
       (q_control_inst_b[9]), .CI (n_158), .CO (n_162), .S (n_163));
  NAND2BXL g3320__3680(.AN (n_159), .B (rst), .Y (n_161));
  NAND2XL g3321__1617(.A (rst), .B (n_159), .Y (n_160));
  ADDFX1 g3322__2802(.A (q_control_inst_a[8]), .B
       (q_control_inst_b[8]), .CI (n_154), .CO (n_158), .S (n_159));
  NAND2BXL g3324__1705(.AN (n_155), .B (rst), .Y (n_157));
  NAND2XL g3325__5122(.A (rst), .B (n_155), .Y (n_156));
  ADDFX1 g3326__8246(.A (q_control_inst_a[7]), .B
       (q_control_inst_b[7]), .CI (n_149), .CO (n_154), .S (n_155));
  NAND2XL g3330__7098(.A (rst), .B (n_150), .Y (n_153));
  OR2XL g3332__6131(.A (n_2), .B (n_150), .Y (n_152));
  XNOR2X1 g3333__1881(.A (q_measurement_inst_q_pulses_count[8]), .B
       (n_140), .Y (n_151));
  ADDFX1 g3334__5115(.A (q_control_inst_a[6]), .B
       (q_control_inst_b[6]), .CI (n_141), .CO (n_149), .S (n_150));
  XNOR2X1 g3337__7482(.A (n_21), .B (n_146), .Y (n_148));
  ADDFX1 g3338__4733(.A (q_measurement_inst_q_pulses_count[3]), .B
       (n_14), .CI (n_138), .CO (n_146), .S (n_147));
  OR2XL g3339__6161(.A (n_2), .B (n_142), .Y (n_145));
  NAND2XL g3341__9315(.A (rst), .B (n_142), .Y (n_144));
  OA21X1 g3342__9945(.A0 (q_measurement_inst_q_pulses_count[7]), .A1
       (n_132), .B0 (n_140), .Y (n_143));
  ADDFX1 g3343__2883(.A (q_control_inst_a[5]), .B
       (q_control_inst_b[5]), .CI (n_133), .CO (n_141), .S (n_142));
  NAND2XL g3346__2346(.A (q_measurement_inst_q_pulses_count[7]), .B
       (n_132), .Y (n_140));
  ADDFX1 g3347__1666(.A (q_measurement_inst_q_pulses_count[2]), .B
       (n_9), .CI (n_130), .CO (n_138), .S (n_139));
  NAND2XL g3348__7410(.A (rst), .B (n_134), .Y (n_137));
  OR2XL g3350__6417(.A (n_2), .B (n_134), .Y (n_136));
  AOI21XL g3351__5477(.A0 (n_9), .A1 (n_124), .B0 (n_132), .Y (n_135));
  ADDFX1 g3352__2398(.A (q_control_inst_a[4]), .B
       (q_control_inst_b[4]), .CI (n_125), .CO (n_133), .S (n_134));
  NOR2XL g3355__5107(.A (n_9), .B (n_124), .Y (n_132));
  ADDFX1 g3356__6260(.A (q_measurement_inst_q_pulses_count[1]), .B
       (n_8), .CI (n_119), .CO (n_130), .S (n_131));
  OR2XL g3357__4319(.A (n_2), .B (n_126), .Y (n_129));
  NAND2XL g3359__8428(.A (rst), .B (n_126), .Y (n_128));
  OA21X1 g3360__5526(.A0 (q_measurement_inst_q_pulses_count[5]), .A1
       (n_117), .B0 (n_124), .Y (n_127));
  ADDFX1 g3361__6783(.A (q_control_inst_a[3]), .B
       (q_control_inst_b[3]), .CI (n_116), .CO (n_125), .S (n_126));
  NAND2XL g3364__3680(.A (q_measurement_inst_q_pulses_count[5]), .B
       (n_117), .Y (n_124));
  NAND2XL g3378__1617(.A (rst), .B (n_118), .Y (n_123));
  OR2XL g3379__2802(.A (n_2), .B (n_118), .Y (n_122));
  XNOR2X1 g3380__1705(.A (n_22), .B (n_93), .Y (n_121));
  AOI21XL g3381__5122(.A0 (n_13), .A1 (n_91), .B0 (n_117), .Y (n_120));
  AOI2BB1X1 g3388__8246(.A0N (q_measurement_inst_q_pulses_count[0]),
       .A1N (n_93), .B0 (q_measurement_inst_q_pulses_count[4]), .Y
       (n_119));
  ADDFX1 g3391__7098(.A (q_control_inst_a[2]), .B
       (q_control_inst_b[2]), .CI (n_92), .CO (n_116), .S (n_118));
  MX2XL g3392__6131(.A (q_control_inst_b[1]), .B (i_ref_w[1]), .S0
       (n_99), .Y (n_115));
  MX2XL g3394__1881(.A (q_control_inst_b[0]), .B (i_ref_w[0]), .S0
       (n_99), .Y (n_114));
  NOR2XL g3397__5115(.A (n_13), .B (n_91), .Y (n_117));
  MX2XL g3399__7482(.A (q_control_inst_b[6]), .B (i_ref_w[6]), .S0
       (n_99), .Y (n_113));
  MX2XL g3400__4733(.A (q_control_inst_b[3]), .B (i_ref_w[3]), .S0
       (n_99), .Y (n_112));
  MX2XL g3401__6161(.A (q_control_inst_b[4]), .B (i_ref_w[4]), .S0
       (n_99), .Y (n_111));
  MX2XL g3402__9315(.A (q_control_inst_b[5]), .B (i_ref_w[5]), .S0
       (n_99), .Y (n_110));
  MX2XL g3403__9945(.A (q_control_inst_b[2]), .B (i_ref_w[2]), .S0
       (n_99), .Y (n_109));
  MX2XL g3404__2883(.A (q_control_inst_b[8]), .B (i_ref_w[8]), .S0
       (n_99), .Y (n_108));
  MX2XL g3405__2346(.A (q_control_inst_b[9]), .B (i_ref_w[9]), .S0
       (n_99), .Y (n_107));
  MX2XL g3406__1666(.A (q_control_inst_b[7]), .B (i_ref_w[7]), .S0
       (n_99), .Y (n_106));
  NAND2X1 g3409__7410(.A (n_42), .B (n_95), .Y (n_105));
  NAND2BXL g3410__6417(.AN (q_control_inst_converged), .B (n_100), .Y
       (n_104));
  NAND2XL g3412__5477(.A (rst), .B (n_94), .Y (n_102));
  OR2XL g3413__2398(.A (n_2), .B (n_94), .Y (n_101));
  NAND3X1 g3414__5107(.A (enable), .B (ready_w), .C (n_86), .Y (n_100));
  AND2X1 g3415__6260(.A (n_89), .B (n_35), .Y (n_103));
  OAI2BB1X1 g3416__4319(.A0N (n_38), .A1N
       (\q_measurement_inst_q_measured[3]_305 ), .B0 (n_88), .Y (n_98));
  AOI21X1 g3417__8428(.A0 (q_measurement_inst_q_pulses_count[3]), .A1
       (n_39), .B0 (n_93), .Y (n_97));
  OA21X1 g3418__5526(.A0 (q_measurement_inst_q_pulses_count[3]), .A1
       (n_40), .B0 (n_91), .Y (n_96));
  AOI22X1 g3419__6783(.A0 (q_measurement_inst_wtd[1]), .A1 (n_87), .B0
       (q_measurement_inst_wtd_lock), .B1 (n_85), .Y (n_95));
  AND2X1 g3420__3680(.A (n_90), .B (n_35), .Y (n_99));
  ADDFX1 g3421__1617(.A (q_control_inst_a[1]), .B
       (q_control_inst_b[1]), .CI (n_19), .CO (n_92), .S (n_94));
  NOR2X1 g3425__2802(.A (q_measurement_inst_q_pulses_count[3]), .B
       (n_39), .Y (n_93));
  NOR2X1 g3426__1705(.A (n_86), .B (q_control_inst_n_919), .Y (n_90));
  NOR2X1 g3427__5122(.A (n_86), .B (q_control_inst_n_902), .Y (n_89));
  OAI211X1 g3428__8246(.A0 (n_7), .A1 (n_17), .B0 (n_37), .C0 (n_39),
       .Y (n_88));
  NAND2XL g3429__7098(.A (q_measurement_inst_q_pulses_count[3]), .B
       (n_40), .Y (n_91));
  NAND2BX1 g3472__6131(.AN (q_measurement_inst_wtd[0]), .B (n_85), .Y
       (n_87));
  NOR4X1 g3473__1881(.A (q_control_inst_error[3]), .B
       (q_control_inst_error[2]), .C (n_24), .D (n_23), .Y (n_86));
  MX2XL g3474__5115(.A (i_ref_sampling_inst_i_ref_smp_3[7]), .B
       (i_ref_sampling_inst_i_ref_smp_4[7]), .S0 (n_16), .Y (n_84));
  NOR2BX1 g3475__7482(.AN (start), .B (n_42), .Y (n_83));
  AOI21XL g3476__4733(.A0 (n_7), .A1 (n_20), .B0 (n_40), .Y (n_82));
  MX2XL g3477__6161(.A (i_ref_w[1]), .B
       (i_ref_sampling_inst_i_ref_smp_1[1]), .S0 (n_16), .Y (n_81));
  MX2XL g3478__9315(.A (i_ref_sampling_inst_i_ref_smp_2[7]), .B
       (i_ref_sampling_inst_i_ref_smp_3[7]), .S0 (n_16), .Y (n_80));
  MX2XL g3479__9945(.A (i_ref_w[8]), .B
       (i_ref_sampling_inst_i_ref_smp_1[8]), .S0 (n_16), .Y (n_79));
  MX2XL g3480__2883(.A (i_ref_w[2]), .B
       (i_ref_sampling_inst_i_ref_smp_1[2]), .S0 (n_16), .Y (n_78));
  MX2XL g3481__2346(.A (i_ref_w[9]), .B
       (i_ref_sampling_inst_i_ref_smp_1[9]), .S0 (n_16), .Y (n_77));
  MX2XL g3482__1666(.A (i_ref_sampling_inst_i_ref_smp_2[9]), .B
       (i_ref_sampling_inst_i_ref_smp_3[9]), .S0 (n_16), .Y (n_76));
  MX2XL g3483__7410(.A (i_ref_sampling_inst_i_ref_smp_3[0]), .B
       (i_ref_sampling_inst_i_ref_smp_4[0]), .S0 (n_16), .Y (n_75));
  MX2XL g3484__6417(.A (i_ref_sampling_inst_i_ref_smp_3[1]), .B
       (i_ref_sampling_inst_i_ref_smp_4[1]), .S0 (n_16), .Y (n_74));
  MX2XL g3485__5477(.A (i_ref_w[3]), .B
       (i_ref_sampling_inst_i_ref_smp_1[3]), .S0 (n_16), .Y (n_73));
  MX2XL g3486__2398(.A (i_ref_sampling_inst_i_ref_smp_3[2]), .B
       (i_ref_sampling_inst_i_ref_smp_4[2]), .S0 (n_16), .Y (n_72));
  MX2XL g3487__5107(.A (i_ref_sampling_inst_i_ref_smp_3[4]), .B
       (i_ref_sampling_inst_i_ref_smp_4[4]), .S0 (n_16), .Y (n_71));
  MX2XL g3488__6260(.A (i_ref_w[4]), .B
       (i_ref_sampling_inst_i_ref_smp_1[4]), .S0 (n_16), .Y (n_70));
  NAND3BXL g3498__4319(.AN (n_18), .B (n_12), .C
       (q_measurement_inst_wtd_lock), .Y (n_85));
  MX2XL g3501__8428(.A (i_ref_w[6]), .B
       (i_ref_sampling_inst_i_ref_smp_1[6]), .S0 (n_16), .Y (n_69));
  MX2XL g3502__5526(.A (i_ref_sampling_inst_i_ref_smp_3[8]), .B
       (i_ref_sampling_inst_i_ref_smp_4[8]), .S0 (n_16), .Y (n_68));
  MX2XL g3503__6783(.A (i_ref_sampling_inst_i_ref_smp_3[9]), .B
       (i_ref_sampling_inst_i_ref_smp_4[9]), .S0 (n_16), .Y (n_67));
  MX2XL g3504__3680(.A (i_ref_w[5]), .B
       (i_ref_sampling_inst_i_ref_smp_1[5]), .S0 (n_16), .Y (n_66));
  MX2XL g3505__1617(.A (i_ref_w[7]), .B
       (i_ref_sampling_inst_i_ref_smp_1[7]), .S0 (n_16), .Y (n_65));
  MX2XL g3506__2802(.A (i_ref_sampling_inst_i_ref_smp_3[5]), .B
       (i_ref_sampling_inst_i_ref_smp_4[5]), .S0 (n_16), .Y (n_64));
  MX2XL g3507__1705(.A (i_ref_sampling_inst_i_ref_smp_1[0]), .B
       (i_ref_sampling_inst_i_ref_smp_2[0]), .S0 (n_16), .Y (n_63));
  MX2XL g3508__5122(.A (i_ref_sampling_inst_i_ref_smp_2[8]), .B
       (i_ref_sampling_inst_i_ref_smp_3[8]), .S0 (n_16), .Y (n_62));
  MX2XL g3509__8246(.A (i_ref_sampling_inst_i_ref_smp_1[1]), .B
       (i_ref_sampling_inst_i_ref_smp_2[1]), .S0 (n_16), .Y (n_61));
  MX2XL g3510__7098(.A (i_ref_sampling_inst_i_ref_smp_2[5]), .B
       (i_ref_sampling_inst_i_ref_smp_3[5]), .S0 (n_16), .Y (n_60));
  MX2XL g3511__6131(.A (i_ref_sampling_inst_i_ref_smp_1[2]), .B
       (i_ref_sampling_inst_i_ref_smp_2[2]), .S0 (n_16), .Y (n_59));
  MX2XL g3512__1881(.A (i_ref_sampling_inst_i_ref_smp_1[3]), .B
       (i_ref_sampling_inst_i_ref_smp_2[3]), .S0 (n_16), .Y (n_58));
  MX2XL g3513__5115(.A (i_ref_sampling_inst_i_ref_smp_1[4]), .B
       (i_ref_sampling_inst_i_ref_smp_2[4]), .S0 (n_16), .Y (n_57));
  MX2XL g3514__7482(.A (i_ref_sampling_inst_i_ref_smp_1[6]), .B
       (i_ref_sampling_inst_i_ref_smp_2[6]), .S0 (n_16), .Y (n_56));
  MX2XL g3515__4733(.A (i_ref_sampling_inst_i_ref_smp_3[3]), .B
       (i_ref_sampling_inst_i_ref_smp_4[3]), .S0 (n_16), .Y (n_55));
  MX2XL g3516__6161(.A (i_ref_sampling_inst_i_ref_smp_1[5]), .B
       (i_ref_sampling_inst_i_ref_smp_2[5]), .S0 (n_16), .Y (n_54));
  MX2XL g3517__9315(.A (i_ref_sampling_inst_i_ref_smp_1[7]), .B
       (i_ref_sampling_inst_i_ref_smp_2[7]), .S0 (n_16), .Y (n_53));
  MX2XL g3518__9945(.A (i_ref_sampling_inst_i_ref_smp_1[8]), .B
       (i_ref_sampling_inst_i_ref_smp_2[8]), .S0 (n_16), .Y (n_52));
  MX2XL g3519__2883(.A (i_ref_sampling_inst_i_ref_smp_1[9]), .B
       (i_ref_sampling_inst_i_ref_smp_2[9]), .S0 (n_16), .Y (n_51));
  MX2XL g3520__2346(.A (i_ref_sampling_inst_i_ref_smp_2[0]), .B
       (i_ref_sampling_inst_i_ref_smp_3[0]), .S0 (n_16), .Y (n_50));
  MX2XL g3521__1666(.A (i_ref_sampling_inst_i_ref_smp_2[1]), .B
       (i_ref_sampling_inst_i_ref_smp_3[1]), .S0 (n_16), .Y (n_49));
  MX2XL g3522__7410(.A (i_ref_sampling_inst_i_ref_smp_2[2]), .B
       (i_ref_sampling_inst_i_ref_smp_3[2]), .S0 (n_16), .Y (n_48));
  MX2XL g3523__6417(.A (i_ref_sampling_inst_i_ref_smp_3[6]), .B
       (i_ref_sampling_inst_i_ref_smp_4[6]), .S0 (n_16), .Y (n_47));
  MX2XL g3524__5477(.A (i_ref_sampling_inst_i_ref_smp_2[3]), .B
       (i_ref_sampling_inst_i_ref_smp_3[3]), .S0 (n_16), .Y (n_46));
  MX2XL g3525__2398(.A (i_ref_sampling_inst_i_ref_smp_2[4]), .B
       (i_ref_sampling_inst_i_ref_smp_3[4]), .S0 (n_16), .Y (n_45));
  MX2XL g3526__5107(.A (i_ref_w[0]), .B
       (i_ref_sampling_inst_i_ref_smp_1[0]), .S0 (n_16), .Y (n_44));
  MX2XL g3527__6260(.A (i_ref_sampling_inst_i_ref_smp_2[6]), .B
       (i_ref_sampling_inst_i_ref_smp_3[6]), .S0 (n_16), .Y (n_43));
  INVX1 g3528(.A (n_38), .Y (n_37));
  INVX1 g3529(.A (n_36), .Y (n_35));
  MX2XL g3530__4319(.A (i_ref_max_w[7]), .B
       (i_ref_sampling_inst_i_ref_smp_4[7]), .S0 (went_unstable_w), .Y
       (n_34));
  MX2XL g3531__8428(.A (i_ref_max_w[3]), .B
       (i_ref_sampling_inst_i_ref_smp_4[3]), .S0 (went_unstable_w), .Y
       (n_33));
  MX2XL g3532__5526(.A (i_ref_max_w[2]), .B
       (i_ref_sampling_inst_i_ref_smp_4[2]), .S0 (went_unstable_w), .Y
       (n_32));
  MX2XL g3533__6783(.A (i_ref_max_w[8]), .B
       (i_ref_sampling_inst_i_ref_smp_4[8]), .S0 (went_unstable_w), .Y
       (n_31));
  NOR2BX1 g3534__3680(.AN (start), .B (n_18), .Y (n_42));
  NOR2BX1 g3535__1617(.AN (n_20), .B (n_17), .Y (n_41));
  NOR2XL g3536__2802(.A (n_7), .B (n_20), .Y (n_40));
  NAND2X1 g3537__1705(.A (n_7), .B (n_17), .Y (n_39));
  NAND2X1 g3538__5122(.A (start), .B (n_18), .Y (n_38));
  OR3X1 g3539__8246(.A (n_10), .B (n_3), .C (q_control_inst_converged),
       .Y (n_36));
  MX2XL g3540__7098(.A (i_ref_max_w[0]), .B
       (i_ref_sampling_inst_i_ref_smp_4[0]), .S0 (went_unstable_w), .Y
       (n_30));
  MX2XL g3541__6131(.A (i_ref_max_w[4]), .B
       (i_ref_sampling_inst_i_ref_smp_4[4]), .S0 (went_unstable_w), .Y
       (n_29));
  MX2XL g3542__1881(.A (i_ref_max_w[5]), .B
       (i_ref_sampling_inst_i_ref_smp_4[5]), .S0 (went_unstable_w), .Y
       (n_28));
  MX2XL g3543__5115(.A (i_ref_max_w[1]), .B
       (i_ref_sampling_inst_i_ref_smp_4[1]), .S0 (went_unstable_w), .Y
       (n_27));
  MX2XL g3544__7482(.A (i_ref_max_w[6]), .B
       (i_ref_sampling_inst_i_ref_smp_4[6]), .S0 (went_unstable_w), .Y
       (n_26));
  MX2XL g3545__4733(.A (i_ref_max_w[9]), .B
       (i_ref_sampling_inst_i_ref_smp_4[9]), .S0 (went_unstable_w), .Y
       (n_25));
  OR4X1 g3546__6161(.A (q_control_inst_error[7]), .B
       (q_control_inst_error[6]), .C (q_control_inst_error[5]), .D
       (q_control_inst_error[4]), .Y (n_24));
  OR4X1 g3547__9315(.A (q_control_inst_error[9]), .B
       (q_control_inst_error[8]), .C (q_control_inst_error[0]), .D
       (q_control_inst_error[1]), .Y (n_23));
  OAI22X1 g3548__9945(.A0 (q_measurement_inst_q_pulses_count[4]), .A1
       (n_6), .B0 (q_measurement_inst_q_pulses_count[0]), .B1 (n_13),
       .Y (n_22));
  MX2XL g3549__2883(.A (q_measurement_inst_q_pulses_count[4]), .B
       (n_13), .S0 (q_measurement_inst_q_pulses_count[8]), .Y (n_21));
  NAND2X1 g3551__2346(.A (q_measurement_inst_q_pulses_count[1]), .B
       (q_measurement_inst_q_pulses_count[0]), .Y (n_20));
  AND2XL g3552__1666(.A (q_control_inst_b[0]), .B
       (q_control_inst_a[0]), .Y (n_19));
  NAND2XL g3553__7410(.A (q_measurement_inst_wtd_lock), .B
       (q_measurement_inst_wtd[0]), .Y (n_15));
  NOR2X1 g3554__6417(.A (q_measurement_inst_wtd[1]), .B
       (q_measurement_inst_wtd[0]), .Y (n_18));
  NOR2X1 g3555__5477(.A (q_measurement_inst_q_pulses_count[1]), .B
       (q_measurement_inst_q_pulses_count[0]), .Y (n_17));
  OR2X2 g3556__2398(.A (went_unstable_w), .B (n_3), .Y (n_16));
  INVX1 g3557(.A (q_measurement_inst_q_pulses_count[7]), .Y (n_14));
  INVX1 g3558(.A (q_measurement_inst_q_pulses_count[4]), .Y (n_13));
  INVXL g3559(.A (q_serialized), .Y (n_12));
  INVX1 g3560(.A (rst), .Y (n_2));
  INVXL g3561(.A (enable), .Y (n_10));
  INVX1 g3562(.A (q_measurement_inst_q_pulses_count[6]), .Y (n_9));
  INVX1 g3563(.A (q_measurement_inst_q_pulses_count[5]), .Y (n_8));
  INVX1 g3564(.A (q_measurement_inst_q_pulses_count[2]), .Y (n_7));
  INVX1 g3565(.A (q_measurement_inst_q_pulses_count[0]), .Y (n_6));
  INVX1 g3566(.A (ready_w), .Y (n_3));
  NAND3X1 g2__5107(.A (n_87), .B (start), .C (n_15), .Y (n_4));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[3] (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (q_measurement_inst_q_pulses_count[3]));
  DFFSHQX1 q_measurement_inst_wtd_lock_reg101(.SN (n_3), .CK
       (q_serialized), .D (1'b0), .Q (q_measurement_inst_wtd_lock));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[1] (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (q_measurement_inst_q_pulses_count[1]));
  DFFRHQX1 q_measurement_inst_wtd_lock_reg(.RN (n_2), .CK (clk), .D
       (1'b0), .Q (q_measurement_inst_wtd_lock));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[0] (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (q_measurement_inst_q_pulses_count[0]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[8] (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (q_measurement_inst_q_pulses_count[8]));
  DFFNSRX1 q_measurement_inst_ready_reg104(.RN (1'b1), .SN (1'b1), .CKN
       (q_serialized), .D (1'b0), .Q (ready_w), .QN (UNCONNECTED29));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[6] (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (q_measurement_inst_q_pulses_count[6]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[5] (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (q_measurement_inst_q_pulses_count[5]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[2] (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (q_measurement_inst_q_pulses_count[2]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[7] (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (q_measurement_inst_q_pulses_count[7]));
  DFFRHQX1 \q_measurement_inst_q_pulses_count_reg[4] (.RN (n_2), .CK
       (clk), .D (1'b0), .Q (q_measurement_inst_q_pulses_count[4]));
  DFFHQX1 \q_measurement_inst_wtd_reg[1]85 (.CK (q_serialized), .D
       (1'b1), .Q (q_measurement_inst_wtd[1]));
  DFFHQX1 \q_measurement_inst_wtd_reg[0]84 (.CK (q_serialized), .D
       (1'b1), .Q (q_measurement_inst_wtd[0]));
  DFFHQX1 q_control_inst_went_unstable_reg111(.CK (ready_w), .D (1'b1),
       .Q (went_unstable_w));
endmodule

