###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Sun Sep 29 15:13:46 2024
#  Design:            top
#  Command:           create_floorplan -site CoreSite -core_density_size 0.968446601942 0.399168 2.6 2.66 2.6 2.66
###############################################################

(globals
    version = 3
    io_order = default
)
